# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odrive_tool.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Odrive(object):
    def setupUi(self, Odrive):
        Odrive.setObjectName("Odrive")
        Odrive.resize(1236, 974)
        self.centralwidget = QtWidgets.QWidget(Odrive)
        self.centralwidget.setObjectName("centralwidget")
        self.Basic_calibration = QtWidgets.QFrame(self.centralwidget)
        self.Basic_calibration.setEnabled(True)
        self.Basic_calibration.setGeometry(QtCore.QRect(180, 60, 691, 661))
        self.Basic_calibration.setFrameShape(QtWidgets.QFrame.Box)
        self.Basic_calibration.setLineWidth(5)
        self.Basic_calibration.setObjectName("Basic_calibration")
        self.configframelabel = QtWidgets.QLabel(self.Basic_calibration)
        self.configframelabel.setGeometry(QtCore.QRect(260, 20, 98, 31))
        self.configframelabel.setObjectName("configframelabel")
        self.layoutWidget = QtWidgets.QWidget(self.Basic_calibration)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 570, 411, 49))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Save_button = QtWidgets.QPushButton(self.layoutWidget)
        self.Save_button.setObjectName("Save_button")
        self.horizontalLayout_8.addWidget(self.Save_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.Calibrate_button = QtWidgets.QPushButton(self.layoutWidget)
        self.Calibrate_button.setObjectName("Calibrate_button")
        self.horizontalLayout_8.addWidget(self.Calibrate_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.axis_conf_Close_button = QtWidgets.QPushButton(self.layoutWidget)
        self.axis_conf_Close_button.setObjectName("axis_conf_Close_button")
        self.horizontalLayout_8.addWidget(self.axis_conf_Close_button)
        self.widget = QtWidgets.QWidget(self.Basic_calibration)
        self.widget.setGeometry(QtCore.QRect(51, 91, 503, 389))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Current_Lim = QtWidgets.QLineEdit(self.widget)
        self.Current_Lim.setObjectName("Current_Lim")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Current_Lim)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.Calibrate_current = QtWidgets.QLineEdit(self.widget)
        self.Calibrate_current.setObjectName("Calibrate_current")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Calibrate_current)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Vel_limit = QtWidgets.QLineEdit(self.widget)
        self.Vel_limit.setObjectName("Vel_limit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Vel_limit)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Brake_resistance = QtWidgets.QLineEdit(self.widget)
        self.Brake_resistance.setObjectName("Brake_resistance")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Brake_resistance)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Pole_pairs = QtWidgets.QLineEdit(self.widget)
        self.Pole_pairs.setObjectName("Pole_pairs")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Pole_pairs)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Encoder_cnt_rev = QtWidgets.QLineEdit(self.widget)
        self.Encoder_cnt_rev.setObjectName("Encoder_cnt_rev")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Encoder_cnt_rev)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.Motor_type = QtWidgets.QComboBox(self.widget)
        self.Motor_type.setObjectName("Motor_type")
        self.Motor_type.addItem("")
        self.Motor_type.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Motor_type)
        self.drive_label = QtWidgets.QLabel(self.centralwidget)
        self.drive_label.setGeometry(QtCore.QRect(90, 10, 501, 31))
        self.drive_label.setFrameShape(QtWidgets.QFrame.Box)
        self.drive_label.setText("")
        self.drive_label.setObjectName("drive_label")
        Odrive.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Odrive)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 43))
        self.menubar.setObjectName("menubar")
        self.menuOdrive_Tool = QtWidgets.QMenu(self.menubar)
        self.menuOdrive_Tool.setObjectName("menuOdrive_Tool")
        self.menuBasic_Config = QtWidgets.QMenu(self.menubar)
        self.menuBasic_Config.setObjectName("menuBasic_Config")
        Odrive.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Odrive)
        self.statusbar.setObjectName("statusbar")
        Odrive.setStatusBar(self.statusbar)
        self.actionFind_any = QtWidgets.QAction(Odrive)
        self.actionFind_any.setObjectName("actionFind_any")
        self.actionFind_on_port = QtWidgets.QAction(Odrive)
        self.actionFind_on_port.setObjectName("actionFind_on_port")
        self.actionexit = QtWidgets.QAction(Odrive)
        self.actionexit.setObjectName("actionexit")
        self.actionAxis0 = QtWidgets.QAction(Odrive)
        self.actionAxis0.setObjectName("actionAxis0")
        self.actionAxis1 = QtWidgets.QAction(Odrive)
        self.actionAxis1.setObjectName("actionAxis1")
        self.menuOdrive_Tool.addAction(self.actionFind_any)
        self.menuOdrive_Tool.addAction(self.actionFind_on_port)
        self.menuOdrive_Tool.addSeparator()
        self.menuOdrive_Tool.addAction(self.actionexit)
        self.menuBasic_Config.addAction(self.actionAxis0)
        self.menuBasic_Config.addAction(self.actionAxis1)
        self.menubar.addAction(self.menuOdrive_Tool.menuAction())
        self.menubar.addAction(self.menuBasic_Config.menuAction())

        self.retranslateUi(Odrive)
        QtCore.QMetaObject.connectSlotsByName(Odrive)

    def retranslateUi(self, Odrive):
        _translate = QtCore.QCoreApplication.translate
        Odrive.setWindowTitle(_translate("Odrive", "Odrive Configuration"))
        self.configframelabel.setText(_translate("Odrive", "Axis 0"))
        self.Save_button.setText(_translate("Odrive", "Save"))
        self.Calibrate_button.setText(_translate("Odrive", "Calibrate"))
        self.axis_conf_Close_button.setText(_translate("Odrive", "Close"))
        self.label.setText(_translate("Odrive", "Current Limit (Amps)"))
        self.Current_Lim.setInputMask(_translate("Odrive", "999.9"))
        self.label_3.setText(_translate("Odrive", "Calibration Current (Amps)"))
        self.Calibrate_current.setInputMask(_translate("Odrive", "99.9"))
        self.label_2.setText(_translate("Odrive", "Velocity Limit (Counts/sec)"))
        self.Vel_limit.setInputMask(_translate("Odrive", "999999"))
        self.label_4.setText(_translate("Odrive", "Brake Resistor (Ohm)"))
        self.Brake_resistance.setInputMask(_translate("Odrive", "9.99"))
        self.label_5.setText(_translate("Odrive", "Pole Pairs"))
        self.Pole_pairs.setInputMask(_translate("Odrive", "99"))
        self.label_7.setText(_translate("Odrive", "Encoder count/rev"))
        self.Encoder_cnt_rev.setInputMask(_translate("Odrive", "999999"))
        self.label_6.setText(_translate("Odrive", "Motor Type"))
        self.Motor_type.setItemText(0, _translate("Odrive", "High Current"))
        self.Motor_type.setItemText(1, _translate("Odrive", "Gimbal"))
        self.menuOdrive_Tool.setTitle(_translate("Odrive", "O&drive Tool"))
        self.menuBasic_Config.setTitle(_translate("Odrive", "Basic Co&nfig"))
        self.actionFind_any.setText(_translate("Odrive", "&Find any"))
        self.actionFind_any.setToolTip(_translate("Odrive", "Find any odrive"))
        self.actionFind_on_port.setText(_translate("Odrive", "Find &on port"))
        self.actionexit.setText(_translate("Odrive", "&exit"))
        self.actionAxis0.setText(_translate("Odrive", "&Axis0"))
        self.actionAxis1.setText(_translate("Odrive", "A&xis1"))

